# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('create_time', models.IntegerField()),
                ('is_delete', models.BooleanField()),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_password', models.CharField(max_length=128)),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
                ('is_delete', models.BooleanField()),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
