# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=64)),
                ('create_time', models.DateTimeField()),
                ('is_delete', models.BooleanField()),
                ('remark', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'consumption_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_password', models.CharField(max_length=128)),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_models.ConsumptionType'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_models.User'),
        ),
    ]
