# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_models', '0002_auto_20180322_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
